### ISSUE TITLE
Full or not full draggable according to a parameter

### ISSUE THREAD

**Issue by Arthur-Milchior** [PureWriter/FullDraggableDrawer#8]
Hi,

Thanks for your library.
I'd like to know if there is a way to decide whether the drawer is draggable from anywhere (as with your library) or only from the side of the screen (as default android), because we discovered that depending on usage, we have users that really want one or really want the other one.

The [best thing](https://github.com/ankidroid/Anki-Android/pull/9015/commits/2e946390fddfac751c019be8f79ebc68880b4209) we have found right now, in our app is to have two .xml files depending on which way we want to use the app, but it's far from ideal. Any help here would be deeply appreciated

I read your readme 
> Advanced usage
See com.drakeet.drawer.FullDraggableHelper

does not really help, I fear the lack of comment, and the fact that I don't know the layout well mean that I don't know what I can do here. But it does not even seem that there is a way for me to control anything from there

**Comment by Orange-Jun** [comment]
Consider utilizing the `setDrawerLockMode()` function to manage the user's actions, which is inherently supported by the `DrawerLayout` component.

```
drawer.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED, Gravity.LEFT);
drawer.setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED, Gravity.LEFT);
```

**Comment by Arthur-Milchior** [comment]
Thank you
